-- MySQL Script generated by MySQL Workbench
-- 11/16/16 20:55:33
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Lana2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Lana2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Lana2` DEFAULT CHARACTER SET utf8 ;
USE `Lana2` ;

-- -----------------------------------------------------
-- Table `Lana2`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Lana2`.`Usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `qtd_validacoes` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lana2`.`Textos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Lana2`.`Textos` (
  `id_texto` INT NOT NULL AUTO_INCREMENT,
  `texto` VARCHAR(255) NULL,
  `classificacao` CHAR(1) NULL,
  `id_usuario` INT NOT NULL,
  `data_validacao` DATETIME NULL,
  PRIMARY KEY (`id_texto`),
  INDEX `fk_Textos_Usuarios_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_Textos_Usuarios`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `Lana2`.`Usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
